import 'normalize.css';
import '@blueprintjs/core/lib/css/blueprint.css';
import '@blueprintjs/icons/lib/css/blueprint-icons.css';

import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Image Annotator',
  description: 'Generated by Lee Hui Ting',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bp5-dark">
      <body>{children}</body>
    </html>
  );
}
